"""Trust Manifest — the exportable proof of what was enforced.

Rivals ground drafts in company content and emit citations a human *may*
check (docs/COMPETITIVE_BENCHMARK.md: nobody machine-enforces truth). This
module turns BidPilot's enforcement into an artifact a reviewer, a customer,
or a contracting officer can audit: every claim -> its KB entry, every
number -> the deterministic code path that computed it, every model call ->
its audit-log fingerprint, plus the gates that actually blocked or passed.

Nothing here is generated by a model. It is assembled from recorded facts;
if the pipeline did not enforce something, the manifest says so.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from .audit import AuditLog
from .models import QASeverity

# Values a model is structurally forbidden from producing (PRD invariant 3).
DETERMINISTIC_PATHS = {
    "wrapped labor rates": "bidpilot/pricing/rates.py:wrap_rate",
    "option-year escalation": "bidpilot/pricing/rates.py:escalate",
    "wage-determination floors": "bidpilot/pricing/rates.py:price_estimate",
    "extended/total price": "bidpilot/pricing/rates.py:price_estimate",
    "exact page counts": "bidpilot/rendering.py:_convert_to_pdf (LibreOffice)",
    "requirement coverage": "bidpilot/qa_checks.py:coverage_check",
    "citation enforcement": "bidpilot/qa_checks.py:citation_check",
    "requirement dedup/IDs": "bidpilot/agents/shredder.py:dedup_requirements",
}


def build_manifest(state, audit_path: Optional[Path] = None) -> dict:
    """Assemble the trust manifest from recorded state — never from a model."""
    claims = _claim_provenance(state)
    pricing = _pricing_proof(state)
    qa = _qa_proof(state)
    gates = [a.model_dump() for a in state.approvals]
    audit = _audit_proof(audit_path)

    return {
        "schema": "bidpilot.trust_manifest/1",
        "run_id": state.run_id,
        "notice_id": state.notice.metadata.notice_id if state.notice else None,
        "guarantees": {
            "never_signed": True,
            "never_submitted": True,
            "certifications_left_blank": True,
            "arithmetic_computed_by_code_not_model": True,
            "uncited_company_claims_block_export": True,
        },
        "claim_provenance": claims,
        "deterministic_computation": {
            "paths": DETERMINISTIC_PATHS,
            "pricing": pricing,
        },
        "quality_gates": qa,
        "human_gates": gates,
        "model_calls": audit,
        "verify_yourself": [
            "Every claim below names the KB entry it came from - open kb/ and read it.",
            "Every priced number came from the named code path, not a model; "
            "re-run `bidpilot reprice` to reproduce it byte-for-byte.",
            "audit.jsonl records each model call with a prompt hash; nothing "
            "reaches the package without appearing there.",
            "HARD QA findings block export - a package that exists passed them.",
        ],
        "disclaimer": (
            "This manifest proves what the system enforced. It does not certify "
            "that the content is correct, competitive, or complete: a human "
            "reviews, resolves [NEEDS INPUT] items, signs, and submits."
        ),
    }


def _claim_provenance(state) -> dict:
    cited, needs_input, uncited, human_edited = [], [], [], []
    for draft in state.section_drafts or []:
        if getattr(draft, "human_edited", False):
            human_edited.append(draft.section_id)
        for claim in getattr(draft, "claims", []) or []:
            row = {"section": draft.section_id, "text": claim.text}
            if claim.kb_source_id:
                cited.append({**row, "kb_source_id": claim.kb_source_id})
            elif claim.needs_input:
                needs_input.append(row)
            else:
                uncited.append(row)
    return {
        "cited": cited,
        "needs_input": needs_input,
        "uncited": uncited,  # must be empty: citation_check blocks export
        "human_edited_sections": human_edited,
        "counts": {
            "cited": len(cited),
            "needs_input": len(needs_input),
            "uncited": len(uncited),
        },
    }


def _pricing_proof(state) -> dict:
    pricing = getattr(state, "pricing", None)
    if not pricing:
        return {"priced": False}
    violations = [v.model_dump() for v in (getattr(pricing, "wd_violations", []) or [])]
    return {
        "priced": True,
        "total": pricing.total,
        "line_items": len(getattr(pricing, "priced_lines", []) or []),
        "wage_determination_violations": violations,
        "wd_compliant": not violations,
    }


def _qa_proof(state) -> dict:
    report = getattr(state, "qa_report", None)
    if not report:
        return {"ran": False}
    findings = getattr(report, "findings", []) or []
    open_hard = [
        f for f in findings if f.severity == QASeverity.HARD and not f.resolved
    ]
    return {
        "ran": True,
        "total_findings": len(findings),
        "open_hard_findings": len(open_hard),
        "hard_findings_block_export": True,
        "open_hard": [
            {"category": f.category, "description": f.description,
             "location": f.location} for f in open_hard
        ],
    }


def _audit_proof(audit_path: Optional[Path]) -> dict:
    if not audit_path or not Path(audit_path).exists():
        return {"audited": False}
    entries = AuditLog(Path(audit_path)).entries()
    calls = [e for e in entries if e.get("event") == "llm_call"]
    failures = [e for e in entries if e.get("event") == "llm_call_failed"]
    models = sorted({e.get("model") for e in calls if e.get("model")})
    return {
        "audited": True,
        "model_calls": len(calls),
        "failed_calls": len(failures),
        "models_used": models,
        "every_call_has_prompt_hash": all(e.get("prompt_sha256") for e in calls),
        "audit_log": "audit.jsonl (not served over the web UI)",
    }


def manifest_markdown(manifest: dict) -> str:
    """Human-readable companion to the JSON — the page a reviewer reads."""
    c = manifest["claim_provenance"]["counts"]
    p = manifest["deterministic_computation"]["pricing"]
    q = manifest["quality_gates"]
    a = manifest["model_calls"]
    lines = [
        "# Trust Manifest",
        "",
        f"Run `{manifest['run_id']}` · notice `{manifest['notice_id']}`",
        "",
        "## What this package guarantees",
        "",
        "- **Never signed, never submitted.** No code path transmits a proposal "
        "or answers a certification.",
        "- **No uncited company claims.** Writer claims name a knowledge-base "
        "entry or carry `[NEEDS INPUT]`; an uncited claim is a HARD failure "
        "that blocks export.",
        "- **Arithmetic is code, not model output.** Rates, escalation, wage "
        "floors, totals, and page counts are computed deterministically.",
        "",
        "## Claim provenance",
        "",
        f"- cited to the knowledge base: **{c['cited']}**",
        f"- marked `[NEEDS INPUT]` (a human must supply): **{c['needs_input']}**",
        f"- uncited: **{c['uncited']}** (must be 0 — export is blocked otherwise)",
    ]
    if manifest["claim_provenance"]["human_edited_sections"]:
        lines.append(
            "- human-edited sections (never auto-redrafted): "
            + ", ".join(manifest["claim_provenance"]["human_edited_sections"])
        )
    lines += ["", "## Deterministic computation", ""]
    for what, where in manifest["deterministic_computation"]["paths"].items():
        lines.append(f"- {what} → `{where}`")
    if p.get("priced"):
        lines += [
            "",
            f"Priced total **${p['total']:,.2f}** across {p['line_items']} line items; "
            f"wage-determination compliant: **{p['wd_compliant']}**"
            + ("" if p["wd_compliant"] else f" ({len(p['wage_determination_violations'])} violations)"),
        ]
    lines += ["", "## Gates", ""]
    if q.get("ran"):
        lines.append(
            f"- QA: {q['total_findings']} findings, "
            f"**{q['open_hard_findings']} open hard** (hard findings block export)"
        )
    for gate in manifest["human_gates"]:
        decision = "approved" if gate.get("approved") else "declined"
        lines.append(
            f"- human gate `{gate.get('gate')}`: **{decision}** by "
            f"{gate.get('actor')} at {gate.get('timestamp')}"
        )
    if a.get("audited"):
        lines += [
            "",
            "## Model calls",
            "",
            f"- {a['model_calls']} calls ({a['failed_calls']} failed), models: "
            + ", ".join(a["models_used"] or ["—"]),
            f"- every call carries a prompt hash: **{a['every_call_has_prompt_hash']}**",
        ]
    lines += ["", "---", "", f"_{manifest['disclaimer']}_"]
    return "\n".join(lines)


def write_trust_manifest(state, audit_path: Optional[Path] = None) -> Path:
    out = Path(state.run_dir)
    manifest = build_manifest(state, audit_path)
    (out / "trust_manifest.json").write_text(
        json.dumps(manifest, indent=2, default=str), encoding="utf-8"
    )
    md = out / "TRUST_MANIFEST.md"
    md.write_text(manifest_markdown(manifest), encoding="utf-8")
    return md
